FROM node:14

# set variables
ENV HOME_ROOT=/opt/app-root
ENV HOME=/opt/app-root/src

RUN mkdir -p $HOME

WORKDIR $HOME_ROOT

WORKDIR $HOME

COPY . .

RUN npm install

# rollback the database migrations
CMD [ "npm", "run", "migrate-rollback" ]
