FROM node:16-slim

RUN apt-get update -y
RUN apt-get install -y g++ make python2

ENV HOME=/opt/app-root/src

RUN mkdir -p $HOME

WORKDIR $HOME

COPY . .

RUN npm install

# run the database migrations and seeding
CMD [ "npm", "run", "setup" ]
