-- populate_government_interest.sql

insert into government_interest (wldtaxonomic_units_id, perceived_risk, rationale) values (2068, 'Poaching and unregulated harvest; Increased harvest efficiency and intensity; overharvest in accessible MUs; Failure to achieve Deer Management Targets', 'Risks are to government interests in maintaining harvest management objectives, minimizing opportunities for illegal harvest or spatially concentrated harvest which may jeopardize local or regional populations. Telemetry data to be available on a need to know basis. Output from telemetry studies will be available at a polygon basis (e.g. UWR). Concerns regarding the overlap of government interests and FN interests in protecting populations to a level that sustains a sustenance, recreational, or commercial harvest. There is a direct link to potential effects on hunter success rates and the implications for decreasing future hunting opportunities.');
insert into government_interest (wldtaxonomic_units_id, perceived_risk, rationale) values (2013, 'Safety Risk to government staff and protesters.', 'Data to be secured for the duration of the government experimental wolf reduction program due to safety issues.');
insert into government_interest (wldtaxonomic_units_id, perceived_risk, rationale) values (2063, 'Poaching Risk', 'Note that all of the point location data were secured under the category of Species Susceptible to Persecution or Harm. Not a substantive risk associated with distributing the herd polygons. Note that there is a need to restructure the Sheep Herd Registry tool to eliminate the distribution of point data. ');
insert into government_interest (wldtaxonomic_units_id, perceived_risk, rationale) values (23921, 'Poaching Risk', 'Note that all of the point location data were secured under the category of Species Susceptible to Persecution or Harm. Not a substantive risk associated with distributing the herd polygons. Note that there is a need to restructure the Sheep Herd Registry tool to eliminate the distribution of point data. ');
insert into government_interest (wldtaxonomic_units_id, perceived_risk, rationale) values (23922, 'Poaching Risk', 'Note that all of the point location data were secured under the category of Species Susceptible to Persecution or Harm. Not a substantive risk associated with distributing the herd polygons. Note that there is a need to restructure the Sheep Herd Registry tool to eliminate the distribution of point data. ');
insert into government_interest (wldtaxonomic_units_id, perceived_risk, rationale) values (4149, 'Rocky Mountain Elk. Risk to integrity of research project; increased risk of illegal harvest', 'Risk to integrity of research project; increased risk of illegal harvest');
insert into government_interest (wldtaxonomic_units_id, perceived_risk, rationale) values (null, 'Modelled Freshwater Fish Habitat Capability Mapping. Draft form; experimental technology. Not validated or field tested. Will this be perceived as government’s advice?', 'Is this an appropriate discussion for this committee? The question for the discussion is whether this is an issue for peer review and timing of making this available vs. protection of government interests. How different is this from other government provided models that are based on data. Maybe the appropriate approach would be to get operational review and provide a context document to accompany the model.');
insert into government_interest (wldtaxonomic_units_id, perceived_risk, rationale) values (null, 'Harvested Species. Increased risk of illegal harvest and potential for increased hunter success rates thus affecting hunter opportunities. Increased risk of inaccurate reporting.', 'Harvested Species	Compulsory Inspection Data	Increased risk of illegal harvest and potential for increased hunter success rates thus affecting hunter opportunities. Increased risk of inaccurate reporting.	Secure	Harvest data are already released in a summary fashion at the MU level. Any species included in this request needs to be consistent with the discussion as for which harvested species point location data (in general) would be secured for. Need to ensure that this is currently publicly available for all harvested species in CIDS.');
insert into government_interest (wldtaxonomic_units_id, perceived_risk, rationale) values (2070, 'Increased risk of illegal harvest and potential for increased hunter success rates thus affecting hunter opportunities.', 'Risks are to government interests in maintaining harvest management objectives, minimizing opportunities for illegal harvest or spatially concentrated harvest which may jeopardize local or regional populations. Point location data to be available on a need to know basis. Output from telemetry studies will be available at a polygon basis (e.g. UWR). Concerns regarding the overlap of government interests and FN interests in protecting populations to a level that sustains a sustenance, recreational, or commercial harvest. There is a direct link to potential effects on hunter success rates and the implications for decreasing future hunting opportunities.');
insert into government_interest (wldtaxonomic_units_id, perceived_risk, rationale) values (2065, 'Increased risk of illegal harvest and potential for increased hunter success rates thus affecting hunter opportunities.', 'Risks are to government interests in maintaining harvest management objectives, minimizing opportunities for illegal harvest or spatially concentrated harvest which may jeopardize local or regional populations. Point location data to be available on a need to know basis. Output from telemetry studies will be available at a polygon basis (e.g. UWR). Concerns regarding the overlap of government interests and FN interests in protecting populations to a level that sustains a sustenance, recreational, or commercial harvest. There is a direct link to potential effects on hunter success rates and the implications for decreasing future hunting opportunities.');
insert into government_interest (wldtaxonomic_units_id, perceived_risk, rationale) values (2037, 'Increased risk of illegal harvest and potential for increased hunter success rates thus affecting hunter opportunities. Risk to integrity of research.', 'Risks are to government interests in maintaining harvest management objectives, minimizing opportunities for illegal harvest or spatially concentrated harvest which may jeopardize local or regional populations. Telemetry data to be available on a need to know basis. Concerns regarding the overlap of government interests and FN interests in protecting populations to a level that sustains a sustenance, recreational, or commercial harvest. There is a direct link to potential effects on hunter success rates and the implications for decreasing future hunting opportunities.');
