---
kind: Template
apiVersion: template.openshift.io/v1
labels:
  app: n8n
  build: "${NAME}"
  template: "${NAME}-bc-template"
metadata:
  name: "${NAME}"
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: "${NAME}"
    spec:
      lookupPolicy:
        local: false
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: "${NAME}"
      labels:
        buildconfig: "${NAME}"
    spec:
      completionDeadlineSeconds: 600
      failedBuildsHistoryLimit: 3
      successfulBuildsHistoryLimit: 3
      output:
        to:
          kind: ImageStreamTag
          name: "${NAME}:${VERSION}"
      postCommit: {}
      resources:
        limits:
          cpu: 0
          memory: 0
        requests:
          cpu: 0
          memory: 0
      runPolicy: SerialLatestOnly
      source:
        dockerfile: |
          FROM BuildConfig
          ENV HOME=/opt/app-root/src \
              TZ=America/Vancouver
          RUN mkdir -p $HOME
          WORKDIR $HOME
          RUN npm install -g n8n
          ENV PATH ${HOME}/node_modules/.bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH
          VOLUME ${HOME}
          VOLUME [ "/data" ]
          WORKDIR /data
          EXPOSE 5678/tcp
          CMD ["n8n"]
        type: Dockerfile
      strategy:
        dockerStrategy:
          from:
            kind: DockerImage
            name: registry.access.redhat.com/ubi8/nodejs-14:latest
        type: Docker
      triggers:
        - type: ConfigChange
parameters:
  - name: NAME
    displayName: Name
    description: The name assigned to all of the objects defined in this template.
    required: true
    value: n8n
  - name: VERSION
    displayName: Image version tag
    description: The version tag of the built image
    required: true
    value: latest
