apiVersion: template.openshift.io/v1
kind: Template
metadata:
  resourceVersion: ''
  selfLink: ''
  name: biohub-platform-queue-dc
parameters:
  - name: NAME
    value: biohub-platform-queue
  - name: SUFFIX
    value: '-dev'
  - name: VERSION
    description: Version of the application
    value: '1.0.0'
  - name: CHANGE_ID
    description: Change id of the project. This will help to pull image stream
    required: true
    value: '0'
  - name: DB_SERVICE_NAME
    description: 'Database service name associated with deployment'
    required: true
  - name: NODE_ENV
    description: Application Environment type variable
    required: true
    value: 'dev'
  - name: S3_KEY_PREFIX
    description: S3 key optional prefix
    required: false
    value: 'platform'
  - name: TZ
    description: Application timezone
    required: false
    value: 'America/Vancouver'
  - name: KEYCLOAK_HOST
    description: Key clock login url
    required: true
  - name: KEYCLOAK_REALM
    description: Realm identifier or name
    required: true
  - name: KEYCLOAK_INTEGRATION_ID
    description: keycloak integration id
    required: true
  - name: KEYCLOAK_API_HOST
    description: keycloak API host
    required: true
  - name: KEYCLOAK_CLIENT_ID
    description: Client Id for application
    required: true
  - name: KEYCLOAK_ADMIN_HOST
    description: Keycloak admin host
    required: true
  - name: KEYCLOAK_ADMIN_USERNAME
    description: keycloak host admin username
    required: true
  - name: KEYCLOAK_SECRET
    description: The name of the keycloak secret
    required: true
  - name: KEYCLOAK_SECRET_ADMIN_PASSWORD
    description: The key of the admin password in the keycloak secret
    required: true
  - name: OBJECT_STORE_SECRETS
    description: Secrets used to read and write to the S3 storage
    value: 'biohubbc-object-store'
  - name: LOG_LEVEL
    value: 'info'
  - name: CPU_REQUEST
    value: '100m'
  - name: CPU_LIMIT
    value: '500m'
  - name: MEMORY_REQUEST
    value: '512Mi'
  - name: MEMORY_LIMIT
    value: '2Gi'
  - name: REPLICAS
    value: '1'
  - name: REPLICA_MAX
    required: true
    value: '1'
objects:
  - kind: ImageStream
    apiVersion: image.openshift.io/v1
    metadata:
      annotations:
        description: Nodejs Runtime Image
      labels:
        shared: 'true'
      creationTimestamp: null
      generation: 0
      name: ${NAME}
    spec:
      lookupPolicy:
        local: false
  - kind: DeploymentConfig
    apiVersion: apps.openshift.io/v1
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
      creationTimestamp: null
      generation: 0
      labels:
        role: queue
      name: ${NAME}${SUFFIX}
    spec:
      replicas: '${{REPLICAS}}'
      revisionHistoryLimit: 10
      selector:
        deploymentConfig: ${NAME}${SUFFIX}
      strategy:
        activeDeadlineSeconds: 21600
        recreateParams:
          timeoutSeconds: 600
        resources:
          limits:
            cpu: ${CPU_LIMIT}
            memory: ${MEMORY_LIMIT}
          requests:
            cpu: ${CPU_REQUEST}
            memory: ${MEMORY_REQUEST}
        type: Rolling
      template:
        metadata:
          annotations: null
          creationTimestamp: null
          labels:
            deploymentConfig: ${NAME}${SUFFIX}
            role: queue
        spec:
          containers:
            - env:
                - name: DB_HOST
                  value: ${DB_SERVICE_NAME}
                - name: DB_USER_API
                  valueFrom:
                    secretKeyRef:
                      key: database-user-api
                      name: ${DB_SERVICE_NAME}
                - name: DB_USER_API_PASS
                  valueFrom:
                    secretKeyRef:
                      key: database-user-api-password
                      name: ${DB_SERVICE_NAME}
                - name: DB_DATABASE
                  valueFrom:
                    secretKeyRef:
                      key: database-name
                      name: ${DB_SERVICE_NAME}
                - name: DB_PORT
                  value: '5432'
                - name: KEYCLOAK_HOST
                  value: ${KEYCLOAK_HOST}
                - name: KEYCLOAK_API_HOST
                  value: ${KEYCLOAK_API_HOST}
                - name: KEYCLOAK_REALM
                  value: ${KEYCLOAK_REALM}
                - name: KEYCLOAK_CLIENT_ID
                  value: ${KEYCLOAK_CLIENT_ID}
                - name: KEYCLOAK_INTEGRATION_ID
                  value: ${KEYCLOAK_INTEGRATION_ID}
                - name: KEYCLOAK_ADMIN_HOST
                  value: ${KEYCLOAK_ADMIN_HOST}
                - name: KEYCLOAK_ADMIN_USERNAME
                  value: ${KEYCLOAK_ADMIN_USERNAME}
                - name: KEYCLOAK_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ${KEYCLOAK_SECRET}
                      key: ${KEYCLOAK_SECRET_ADMIN_PASSWORD}
                - name: CHANGE_VERSION
                  value: ${CHANGE_ID}
                - name: NODE_ENV
                  value: ${NODE_ENV}
                - name: S3_KEY_PREFIX
                  value: ${S3_KEY_PREFIX}
                - name: TZ
                  value: ${TZ}
                - name: VERSION
                  value: ${VERSION}
                - name: OBJECT_STORE_URL
                  valueFrom:
                    secretKeyRef:
                      key: object_store_url
                      name: ${OBJECT_STORE_SECRETS}
                - name: OBJECT_STORE_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      key: object_store_access_key_id
                      name: ${OBJECT_STORE_SECRETS}
                - name: OBJECT_STORE_SECRET_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      key: object_store_secret_key_id
                      name: ${OBJECT_STORE_SECRETS}
                - name: OBJECT_STORE_BUCKET_NAME
                  valueFrom:
                    secretKeyRef:
                      key: object_store_bucket_name
                      name: ${OBJECT_STORE_SECRETS}
                - name: LOG_LEVEL
                  value: ${LOG_LEVEL}
              image: ' '
              imagePullPolicy: Always
              name: queue
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
                - mountPath: /opt/app-root/app
                  name: ${NAME}${SUFFIX}
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
            - emptyDir: {}
              name: ${NAME}${SUFFIX}
      test: false
      triggers:
        - imageChangeParams:
            automatic: true
            containerNames:
              - queue
            from:
              kind: ImageStreamTag
              name: ${NAME}:${VERSION}
          type: ImageChange
        - type: ConfigChange
    status:
      availableReplicas: 0
      latestVersion: 0
      observedGeneration: 0
      replicas: 0
      unavailableReplicas: 0
      updatedReplicas: 0
  - kind: Secret
    apiVersion: v1
    stringData:
      database-name: ''
      database-user-api-password: ''
      database-user-api: ''
    metadata:
      annotations:
        as-copy-of: ${DB_SERVICE_NAME}
      creationTimestamp: null
      name: ${NAME}${SUFFIX}
    type: Opaque
  - kind: HorizontalPodAutoscaler
    apiVersion: autoscaling/v1
    metadata:
      annotations: {}
      creationTimestamp: null
      labels: {}
      name: ${NAME}${SUFFIX}
    spec:
      maxReplicas: '${{REPLICA_MAX}}'
      minReplicas: '${{REPLICAS}}'
      scaleTargetRef:
        apiVersion: v1
        kind: DeploymentConfig
        name: ${NAME}${SUFFIX}
      cpuUtilization:
        targetPercentage: 95
