replicas: 1

resources:
  requests:
    cpu: 250m
    memory: 1Gi
  limits:
    cpu: "2"
    memory: 3Gi

clamd:
  logVerbose: false
  streamMaxLength: 2000M
  maxFileSize: 2000M
  maxScanSize: 2000M
