FROM node:14

# set variables
ENV HOME_ROOT=/opt/app-root
ENV HOME=/opt/app-root/src

RUN mkdir -p $HOME

WORKDIR $HOME_ROOT

WORKDIR $HOME

COPY . .

RUN npm install

# run the database migrations and seeding
CMD [ "npm", "run", "import" ]
