FROM node:16.13.0-alpine

RUN apk update && apk add python2 make g++

# set variables
ENV HOME=/opt/app-root/src

RUN mkdir -p $HOME

WORKDIR $HOME

ENV PATH $HOME/node_modules/.bin:$PATH

COPY . .

# If you are building your code for production
# RUN npm install --only=production
# RUN npm set progress=false
RUN npm install

# run the database migrations and seeding
CMD [ "npm", "run", "export" ]
