apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clamav.fullname" . }}-config
  labels:
    {{- include "clamav.labels" . | nindent 4 }}
data:
  clamd.conf: |
    LogFile {{ .Values.clamd.logFile }}
    LogTime {{ ternary "yes" "no" .Values.clamd.logTime }}
    LogClean {{ ternary "yes" "no" .Values.clamd.logClean }}
    LogVerbose {{ ternary "yes" "no" .Values.clamd.logVerbose }}
    LogSyslog {{ ternary "yes" "no" .Values.clamd.logSyslog }}
    TCPSocket {{ .Values.clamd.tcpSocket }}
    StreamMaxLength {{ .Values.clamd.streamMaxLength }}
    MaxFileSize {{ .Values.clamd.maxFileSize }}
    MaxScanSize {{ .Values.clamd.maxScanSize }}
    MaxThreads {{ .Values.clamd.maxThreads }}
    MaxConnectionQueueLength {{ .Values.clamd.maxConnectionQueueLength }}
    ReadTimeout {{ .Values.clamd.readTimeout }}
    SelfCheck {{ .Values.clamd.selfCheck }}
    AllowSupplementaryGroups {{ ternary "yes" "no" .Values.clamd.allowSupplementaryGroups }}
    Foreground {{ ternary "yes" "no" .Values.clamd.foreground }}
    DatabaseDirectory /var/lib/clamav
    {{- range .Values.clamd.extraDirectives }}
    {{ . }}
    {{- end }}
  freshclam.conf: |
    DatabaseDirectory /var/lib/clamav
    DatabaseOwner clamav
    LogTime yes
    Foreground yes
    {{- with .Values.freshclam.databaseMirror }}
    DatabaseMirror {{ . }}
    {{- end }}
