apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: biohub-platform-geoserver
  labels:
    build: biohub-platform-geoserver
annotations:
  iconClass: icon-tomcat
parameters:
  - name: NAME
    displayName: Name
    description: The name assigned to all of the resources.
    required: true
    value: biohub-platform-geoserver
  - name: TARGET_IMAGE_VERSION
    required: true
  - name: SOURCE_IMAGE_NAME
    required: true
    value: geoserver
  - name: SOURCE_IMAGE_VERSION
    required: true
    value: 2.21.1
  - name: SOURCE_IMAGE_NAMESPACE
    required: true
    value: a0ec71-tools
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: '${NAME}'
      labels:
        shared: 'true'
      annotations: {}
    spec:
      lookupPolicy:
        local: false
      tags:
        - name: '${TARGET_IMAGE_VERSION}'
          annotations:
          from:
            kind: ImageStreamTag
            name: ${SOURCE_IMAGE_NAME}:latest
            namespace: ${SOURCE_IMAGE_NAMESPACE}
          generation: 1
          importPolicy: {}
          referencePolicy:
            type: Source
      successfulBuildsHistoryLimit: 5
      triggers:
        - type: ImageChange
          imageChange:
            from:
              kind: ImageStreamTag
              name: ${SOURCE_IMAGE_NAME}:latest
              namespace: ${SOURCE_IMAGE_NAMESPACE}
