apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: biohub-platform-geoserver
  labels:
    build: biohub-platform-geoserver
annotations:
  iconClass: icon-tomcat
parameters:
  - name: NAME
    displayName: Name
    description: The name assigned to all of the resources.
    required: true
    value: biohub-platform-geoserver
  - name: SUFFIX
    displayName: Name Suffix
    description: A suffix appended to all objects
    required: true
    value: ''
  - name: TARGET_IMAGE_VERSION
    required: true
  - name: SOURCE_IMAGE_NAME
    required: true
    value: geoserver
  - name: SOURCE_IMAGE_VERSION
    required: true
    value: 2.21.1
  - name: SOURCE_IMAGE_NAMESPACE
    required: true
    value: a0ec71-tools
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: '${NAME}'
      labels:
        shared: 'true'
      annotations: {}
    spec:
      lookupPolicy:
        local: false
      tags:
        - name: '${TARGET_IMAGE_VERSION}'
          annotations:
          from:
            kind: ImageStreamTag
            name: '${SOURCE_IMAGE_NAME}:${SOURCE_IMAGE_VERSION}'
            namespace: ${SOURCE_IMAGE_NAMESPACE}
          generation: 1
          importPolicy: {}
          referencePolicy:
            type: Source
# apiVersion: template.openshift.io/v1
# kind: Template
# metadata:
#   name: biohubbc-geoserver
#   labels:
#     build: biohubbc-geoserver
# parameters:
#   - name: NAME
#     displayName: Name
#     description: The name assigned to all of the resources.
#     required: true
#     value: biohubbc-geoserver
#   - name: SUFFIX
#     displayName: Name Suffix
#     description: A suffix appended to all objects
#     required: true
#     value: ''
#   - name: TARGET_IMAGE_VERSION
#     required: true
#   # - name: SOURCE_IMAGE_NAME
#   #   required: true
#   #   value: geoserver
#   # - name: SOURCE_IMAGE_VERSION
#   #   required: true
#   #   value: 2.21.1
#   # - name: SOURCE_IMAGE_NAMESPACE
#   #   required: true
#   #   value: a0ec71-tools
# objects:
#   # - kind: ImageStream
#   #   apiVersion: image.openshift.io/v1
#   #   metadata:
#   #     name: debian
#   #   spec:
#   #     lookupPolicy:
#   #       local: false
#   #     tags:
#   #       - name: bullseye
#   #         annotations:
#   #           openshift.io/imported-from: 'debian:bullseye'
#   #         from:
#   #           kind: DockerImage
#   #           name: 'debian:bullseye'
#   #         generation: 2
#   #         importPolicy: {}
#   #         referencePolicy:
#   #           type: Source

#   - kind: ImageStream
#     apiVersion: v1
#     metadata:
#       name: '${NAME}'
#       labels:
#         shared: 'true'
#     spec:
#       lookupPolicy:
#         local: false

#   - kind: BuildConfig
#     apiVersion: build.openshift.io/v1
#     metadata:
#       name: '${NAME}${SUFFIX}'
#       labels: {}
#       annotations: {}
#     spec:
#       nodeSelector: null
#       postCommit: {}
#       resources: {}
#       successfulBuildsHistoryLimit: 5
#       failedBuildsHistoryLimit: 5
#       runPolicy: Serial
#       strategy:
#         type: Docker
#         dockerStrategy:
#           dockerfilePath: Dockerfile
#       source:
#         type: Git
#         git:
#           uri: 'https://github.com/geoserver/docker.git'
#           ref: master
#         contextDir: /
#       output:
#         to:
#           kind: ImageStreamTag
#           name: '${NAME}:${TARGET_IMAGE_VERSION}'
#       triggers:
#         - type: ConfigChange
#         - type: ImageChange
