# Pull Request environment values for Biohub. This template will be used for dynamic PR deployments
environment:
  name: dev
  # id will be dynamically set: "1234"

# Database configuration
app:
  nodeEnv: development
