kind: Template
apiVersion: template.openshift.io/v1
description: A build config template that can be used to produce a GeoServer imagestream, from a specified Dockerfile.
metadata:
  labels:
    build: geoserver
  name: geoserver
parameters:
  - name: NAME
    description: The name assigned to all of the resources.
    required: true
    value: geoserver
  - name: SUFFIX
    description: A name suffix used for all objects
    required: false
    value: ""
  - name: APP_NAME
    description: Used to group components together in the OpenShift console.
    required: true
    value: geoserver
  - name: APP_GROUP
    description: The name assigned to all of the deployments in this project.
    required: true
    value: biohubbc
  - name: GIT_REPO_URL
    description: The git repo containing the Dockerfile for this build.
    required: true
    value: https://github.com/bcgov/biohubbc-platform.git
  - name: GIT_REF
    description: The specific repo reference (eg. dev, 1.0.0, <commit sha>)
    required: true
    value: dev
  - name: SOURCE_CONTEXT_DIR
    description: The repository path to the Dockerfile.
    required: true
    value: Containers/geoserver/geodock
  - name: DOCKERFILE_PATH
    description: The path to the docker file (note. this is relative to the SOURCE_CONTEXT_DIR).
    required: true
    value: Dockerfile
  - name: GEOSERVER_VERSION
    description: Geoserver version, used as the image tag.
    required: true
    value: 2.21.1
  - name: CPU_LIMIT
    description: The resources CPU limit (in cores) for this build; 0 = use default.
    required: true
    value: "0"
  - name: MEMORY_LIMIT
    description: The resources Memory limit (in Mi, Gi, etc) for this build; 0Mi = use default.
    required: true
    value: 0Mi
  - name: CPU_REQUEST
    description: The resources CPU request (in cores) for this build; 0 = use default.
    required: true
    value: "0"
  - name: MEMORY_REQUEST
    description: The resources Memory request (in Mi, Gi, etc) for this build; 0Mi = use default.
    required: true
    value: 0Mi
objects:
  - kind: ImageStream
    apiVersion: image.openshift.io/v1
    metadata:
      name: ${NAME}
      labels:
        name: ${NAME}
        app: ${APP_NAME}${SUFFIX}
        app-group: ${APP_GROUP}
  - kind: BuildConfig
    apiVersion: build.openshift.io/v1
    metadata:
      name: ${NAME}
      labels:
        name: ${NAME}
        app: ${APP_NAME}${SUFFIX}
        app-group: ${APP_GROUP}
    spec:
      runPolicy: Serial
      source:
        type: Git
        git:
          uri: ${GIT_REPO_URL}
          ref: ${GIT_REF}
        contextDir: ${SOURCE_CONTEXT_DIR}
      strategy:
        type: Docker
        dockerStrategy:
          dockerfilePath: "${DOCKERFILE_PATH}"
      output:
        to:
          kind: ImageStreamTag
          name: "${NAME}:${GEOSERVER_VERSION}"
      resources:
        requests:
          cpu: ${CPU_REQUEST}
          memory: ${MEMORY_REQUEST}
        limits:
          cpu: ${CPU_LIMIT}
          memory: ${MEMORY_LIMIT}
