apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: postgresql
  labels:
    build: postgresql
parameters:
  - name: NAME
    displayName: Name
    description: A name used for all objects
    required: true
  - name: SUFFIX
    displayName: Name Suffix
    description: A suffix appended to all objects
    required: true
  - name: TAG_NAME
    required: true
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: '${NAME}'
      labels:
        shared: 'true'
      annotations: {}
    spec:
      lookupPolicy:
        local: false
      tags:
        - name: '${TAG_NAME}'
          annotations:
          from:
            kind: ImageStreamTag
            name: crunchy-postgres-gis:ubi8-14.2-3.1-0
            namespace: a0ec71-tools
          generation: 1
          importPolicy: {}
          referencePolicy:
            type: Source
